cvm-version: 0.10.4
cpus: 2
memory: 2048

containers:
  - name: "metadata-fetch"
    image: "ghcr.io/tinfoilsh/confidential-website-metadata-fetcher@sha256:99c0f8bc82ab467f4e9824d0c0c4e8c8bc2d634a1b8e1a6c364747d0b0491f63" # v0.0.6
    restart: always
    networks: [zyte]
    secrets:
      - ZYTE_API_KEY

networks:
  zyte:
    egress: allowlist
    allow:
      - api.zyte.com

shim:
  upstream-port: 8089
  paths:
    - /metadata
    - /health
