cvm-version: 0.10.4
cpus: 2
memory: 2048

containers:
  - name: "metadata-fetch"
    image: "ghcr.io/tinfoilsh/confidential-website-metadata-fetcher@sha256:d406a5c3b1c3d40a929c3ebf4350c9f0b6cc989203c30b8739f398d3bb44a37d" # v0.0.8
    restart: always
    networks: [outbound]
    secrets:
      - ZYTE_API_KEY

networks:
  outbound:
    egress: allowlist
    allow:
      - api.zyte.com
      - icons.duckduckgo.com

shim:
  upstream-port: 8089
  paths:
    - /metadata
    - /favicon
    - /health
